<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="33" started-at="2019-02-28T12:38:36Z" finished-at="2019-02-28T12:38:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="33" started-at="2019-02-28T12:38:36Z" finished-at="2019-02-28T12:38:36Z">
      <class name="Automationtesting1.Automationtesting1.LoginPageTest">
        <test-method status="FAIL" signature="setup()[pri:0, instance:Automationtesting1.Automationtesting1.LoginPageTest@74f0ea28]" name="setup" is-config="true" duration-ms="0" started-at="2019-02-28T18:08:36Z" finished-at="2019-02-28T18:08:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Com_Automationtesting1_testbase.TestBase.initalization(TestBase.java:51)
	at Automationtesting1.Automationtesting1.LoginPageTest.setup(LoginPageTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="EnterwithvalidUserNameTest()[pri:0, instance:Automationtesting1.Automationtesting1.LoginPageTest@74f0ea28]" name="EnterwithvalidUserNameTest" duration-ms="2" started-at="2019-02-28T18:08:36Z" finished-at="2019-02-28T18:08:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EnterwithvalidUserNameTest -->
      </class> <!-- Automationtesting1.Automationtesting1.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
